export const vocab = [
{pl: "źródło", en: "a source", scope: "bhp-osp-it"},
{pl: "członek rodziny", en: "a family member", scope: "bhp-osp-it"},
{pl: "napaść, atak", en: "an attack", scope: "bhp-osp-it"},
{pl: "koń trojański", en: "a trojan horse", scope: "bhp-osp-it"},
{pl: "kraść", en: "to steal", scope: "bhp-osp-it"},
{pl: "zawierać", en: "to contain", scope: "bhp-osp-it"},
{pl: "oszukańczy", en: "fraudulent", scope: "bhp-osp-it"},
{pl: "niepożądany, natrętny", en: "intrusive", scope: "bhp-osp-it"},
{pl: "niedoskonałość", en: "an imperfection", scope: "bhp-osp-it"},
{pl: "mieć dostęp", en: "to access", scope: "bhp-osp-it"},
{pl: "poprawka", en: "a patch", scope: "bhp-osp-it"},
{pl: "zakres", en: "a scope of", scope: "bhp-osp-it"},
{pl: "albo … albo …", en: "either … or …", scope: "bhp-osp-it"},
{pl: "unieruchamiać, blokować", en: "to disable", scope: "bhp-osp-it"},
{pl: "przekręt", en: "a scam", scope: "bhp-osp-it"},
{pl: "ilość", en: "an amount of", scope: "bhp-osp-it"},
{pl: "na przecenie", en: "at a discount", scope: "bhp-osp-it"},
{pl: "w zamian", en: "in return", scope: "bhp-osp-it"},
{pl: "prosić się o kłopoty", en: "to ask for trouble", scope: "bhp-osp-it"},
{pl: "uzyskać dostęp do czegoś", en: "to get access to sth", scope: "bhp-osp-it"},
{pl: "trwać wieki", en: "to last forever", scope: "bhp-osp-it"},
{pl: "chociaż", en: "although", scope: "bhp-osp-it"},
{pl: "wielkie litery", en: "upper case letters", scope: "bhp-osp-it"},
{pl: "liczebnik", en: "a numeral", scope: "bhp-osp-it"},
{pl: "nie do pobicia", en: "unbeatable", scope: "bhp-osp-it"},
{pl: "mający reputację", en: "reputable", scope: "bhp-osp-it"},
{pl: "zamieszczać w internecie", en: "to post", scope: "bhp-osp-it"},
{pl: "sprawdzona zasada", en: "a rule of thumb", scope: "bhp-osp-it"},
{pl: "przywłaszczenie tożsamości", en: "an identity theft", scope: "bhp-osp-it"},
{pl: "powiadomienie", en: "a notification", scope: "bhp-osp-it"},
{pl: "tarcza", en: "a shield", scope: "bhp-osp-it"},
{pl: "ustawiać", en: "to configure", scope: "bhp-osp-it"},
{pl: "interfejs", en: "an interface", scope: "bhp-osp-it"},
{pl: "intruz", en: "an intruder", scope: "bhp-osp-it"},
{pl: "zapora sieciowa", en: "a firewall", scope: "bhp-osp-it"},
{pl: "kliknąć prawym przyciskiem myszy", en: "to right-click", scope: "bhp-osp-it"},
{pl: "porównywać", en: "to compare", scope: "bhp-osp-it"},
{pl: "załącznik", en: "an attachment", scope: "bhp-osp-it"},
{pl: "trzymać kogoś z dala", en: "to keep sb away", scope: "bhp-osp-it"},
{pl: "umiejscowić", en: "to place", scope: "bhp-osp-it"},
{pl: "słaby punkt", en: "a vulnerability", scope: "bhp-osp-it"},
{pl: "odkryć", en: "to discover", scope: "bhp-osp-it"},
{pl: "rozległy, nieprzebrany", en: "vast", scope: "bhp-osp-it"},
{pl: "samokopiujący się", en: "self-replication", scope: "bhp-osp-it"},
{pl: "na szczęście", en: "luckily", scope: "bhp-osp-it"},
{pl: "żart, oszustwo", en: "a hoax", scope: "bhp-osp-it"},
{pl: "fałszywy", en: "fake", scope: "bhp-osp-it"},
{pl: "próg", en: "a doorstep", scope: "bhp-osp-it"},
{pl: "apteka", en: "a pharmacy", scope: "bhp-osp-it"},
{pl: "przesłać dalej", en: "to forward", scope: "bhp-osp-it"},
{pl: "włamać się do", en: "to break into", scope: "bhp-osp-it"},
{pl: "kluczowy", en: "key", scope: "bhp-osp-it"},
{pl: "postawić hipotezę", en: "to make an educated guess", scope: "bhp-osp-it"},
{pl: "losowy", en: "random", scope: "bhp-osp-it"},
{pl: "małe litery", en: "lower case letters", scope: "bhp-osp-it"},
{pl: "znak interpunkcyjny", en: "a punctuation mark", scope: "bhp-osp-it"},
{pl: "szyfrować", en: "to encrypt", scope: "bhp-osp-it"},
{pl: "jednakże", en: "however", scope: "bhp-osp-it"},
{pl: "obcy", en: "a stranger", scope: "bhp-osp-it"},
{pl: "unikać", en: "to avoid", scope: "bhp-osp-it"},
{pl: "prosty", en: "straightforward", scope: "bhp-osp-it"},
{pl: "domyślnie", en: "by default", scope: "bhp-osp-it"},
{pl: "wprowadzać na rynek", en: "to launch", scope: "bhp-osp-it"},
{pl: "złośliwy", en: "malicious", scope: "bhp-osp-it"},
{pl: "w czasie rzeczywistym", en: "in real-time", scope: "bhp-osp-it"},
{pl: "śledzić, obserwować", en: "to monitor", scope: "bhp-osp-it"},
{pl: "oprogramowanie szantażujące", en: "ransomware", scope: "bhp-osp-it"},
{pl: "dwukrotnie kliknąć", en: "to double-click", scope: "bhp-osp-it"},
{pl: "bot", en: "a bot", scope: "bhp-osp-it"},
{pl: "program szpiegujący", en: "spyware", scope: "bhp-osp-it"},
{pl: "wymagać, angażować", en: "to involve", scope: "bhp-osp-it"},
{pl: "ukrywać", en: "to mask", scope: "bhp-osp-it"},
{pl: "wywoływać alarm", en: "to alert", scope: "bhp-osp-it"},
{pl: "zdalnie", en: "remotely", scope: "bhp-osp-it"},
{pl: "rootkit", en: "a rootkit", scope: "bhp-osp-it"},
{pl: "popełnić przestępstwo", en: "to commit a crime", scope: "bhp-osp-it"},
{pl: "osadzać, wbudować", en: "to embed", scope: "bhp-osp-it"},
{pl: "złośliwe oprogramowanie", en: "malware", scope: "bhp-osp-it"},
{pl: "przejąć kontrolę", en: "to take over", scope: "bhp-osp-it"},
{pl: "zarazić, zainfekować", en: "to infect", scope: "bhp-osp-it"},
{pl: "robak komputerowy", en: "a computer worm", scope: "bhp-osp-it"},
{pl: "wykryć", en: "to detect", scope: "bhp-osp-it"},
{pl: "wiadomość błyskawiczna", en: "an instant message", scope: "bhp-osp-it"},

{pl:"ubiegać się o pracę", en:"apply for a job", scope:"job-search"},
{pl:"źle płatny", en:"badly paid", scope:"work-conditions"},
{pl:"być zatrudnionym", en:"be employed", scope:"employment"},
{pl:"samozatrudniony", en:"self-employed", scope:"employment"},
{pl:"być odpowiedzialnym za", en:"be responsible for", scope:"employment"},
{pl:"bezrobotny", en:"unemployed", scope:"employment"},
{pl:"dobrze płatny", en:"well-paid", scope:"work-conditions"},
{pl:"stanowić wyzwanie", en:"challenging", scope:"traits"},
{pl:"wymyślić", en:"come up with", scope:"actions"},
{pl:"kreatywny", en:"creative", scope:"skills"},
{pl:"wymagający", en:"demanding", scope:"work-conditions"},
{pl:"pracować długo", en:"work long hours", scope:"work-conditions"},
{pl:"pracować na nocne zmiany", en:"work night shifts", scope:"work-conditions"},
{pl:"pracować w nadgodzinach", en:"work overtime", scope:"work-conditions"},
{pl:"zatrudniać", en:"employ", scope:"employment"},
{pl:"pracodawca", en:"employer", scope:"employment"},
{pl:"praca na pełny etat", en:"full-time job", scope:"employment"},
{pl:"zostać zwolnionym", en:"get fired", scope:"employment"},
{pl:"dostać dzień wolny", en:"get/have/take a day off", scope:"work-conditions"},
{pl:"mieć płatny urlop", en:"have paid holiday", scope:"work-conditions"},
{pl:"mieć pracę", en:"have a job", scope:"employment"},
{pl:"praca na część etatu", en:"part-time job", scope:"employment"},
{pl:"odłożyć coś", en:"put sth off", scope:"actions"},
{pl:"znieść coś", en:"put up with", scope:"actions"},
{pl:"powtarzalny", en:"repetitive", scope:"work-conditions"},
{pl:"zrezygnować z pracy", en:"resign from a job", scope:"employment"},
{pl:"satysfakcjonujący", en:"rewarding", scope:"traits"},
{pl:"prowadzić firmę", en:"run a business", scope:"employment"},
{pl:"stresujący", en:"stressful", scope:"traits"},
{pl:"zatrudnić kogoś", en:"take sb on", scope:"employment"},
{pl:"męczący", en:"tiring", scope:"traits"},
{pl:"pojawić się", en:"turn up", scope:"actions"},
{pl:"doświadczenie zawodowe", en:"work experience", scope:"education"},
{pl:"pracować w pomieszczeniu", en:"work indoors", scope:"workplace"},
{pl:"pracować na zewnątrz", en:"work outdoors", scope:"workplace"},

// jobs
{pl:"opiekunka do dziecka", en:"babysitter", scope:"jobs"},
{pl:"opiekun osób starszych", en:"carer", scope:"jobs"},
{pl:"ratownik", en:"lifeguard", scope:"jobs"},
{pl:"handel detaliczny", en:"retail", scope:"workplace"},
{pl:"przejść na emeryturę", en:"retire", scope:"employment"},
{pl:"wziąć wolne", en:"take time off", scope:"work-conditions"},
{pl:"pracować z domu", en:"work from home", scope:"workplace"},
{pl:"pracować na zewnątrz", en:"work outside", scope:"workplace"},

// more jobs
{pl:"pilot", en:"airline pilot", scope:"jobs"},
{pl:"ambitny", en:"ambitious", scope:"traits"},
{pl:"pracować zdalnie", en:"work from home", scope:"workplace"},
{pl:"kosmetyczka", en:"beautician", scope:"jobs"},
{pl:"korzyść", en:"benefit", scope:"employment"},
{pl:"odważny", en:"brave", scope:"traits"},

// jobs section big list
{pl:"kierowca autobusu", en:"bus driver", scope:"jobs"},
{pl:"stolarz", en:"carpenter", scope:"jobs"},
{pl:"sprytny", en:"clever", scope:"traits"},
{pl:"szkolić się", en:"do training", scope:"education"},
{pl:"instruktor jazdy", en:"driving instructor", scope:"jobs"},
{pl:"elektryk", en:"electrician", scope:"jobs"},
{pl:"inżynier", en:"engineer", scope:"jobs"},
{pl:"agent nieruchomości", en:"estate agent", scope:"jobs"},
{pl:"dobrze dogadywać się", en:"get on well with", scope:"skills"},
{pl:"mieć doskonały wzrok", en:"have excellent eyesight", scope:"skills"},
{pl:"tłumacz", en:"interpreter", scope:"jobs"},
{pl:"dziennikarz", en:"journalist", scope:"jobs"},
{pl:"ratownik", en:"lifeguard", scope:"jobs"},
{pl:"zdominowany przez mężczyzn", en:"male-dominated job", scope:"workplace"},
{pl:"praca fizyczna", en:"manual job", scope:"jobs"},
{pl:"muzyk", en:"musician", scope:"jobs"},
{pl:"biuro", en:"office", scope:"workplace"},
{pl:"asystent biurowy", en:"office assistant", scope:"jobs"},
{pl:"umiejętności osobiste", en:"personal skills", scope:"skills"},
{pl:"praktyczny", en:"practical", scope:"skills"},
{pl:"awans", en:"promotion", scope:"employment"},
{pl:"recepcjonista", en:"receptionist", scope:"jobs"},
{pl:"wynagrodzenie", en:"salary", scope:"employment"},
{pl:"sekretarka", en:"secretary", scope:"jobs"},
{pl:"sprzedawca", en:"shop assistant", scope:"jobs"},
{pl:"instruktor narciarstwa", en:"skiing instructor", scope:"jobs"},
{pl:"specjalista", en:"specialist", scope:"jobs"},
{pl:"taksówkarz", en:"taxi driver", scope:"jobs"},
{pl:"agent turystyczny", en:"travel agent", scope:"jobs"},
{pl:"dyplom uniwersytecki", en:"university degree", scope:"education"},

// traits & personality
{pl:"aktywny", en:"active", scope:"traits"},
{pl:"ambicja", en:"ambition", scope:"traits"},
{pl:"ambitny", en:"ambitious", scope:"traits"},
{pl:"biznesmen", en:"businessperson", scope:"jobs"},
{pl:"urok", en:"charm", scope:"traits"},
{pl:"czarujący", en:"charming", scope:"traits"},
{pl:"rywalizować", en:"compete", scope:"actions"},
{pl:"rywalizacja", en:"competition", scope:"traits"},
{pl:"konkurencyjny", en:"competitive", scope:"traits"},
{pl:"decydent", en:"decision-maker", scope:"jobs"},
{pl:"projektant", en:"designer", scope:"jobs"},
{pl:"determinacja", en:"determination", scope:"traits"},
{pl:"zdeterminowany", en:"determined", scope:"traits"},
{pl:"dyrektor", en:"director", scope:"jobs"},
{pl:"strażak", en:"fire-fighter", scope:"jobs"},
{pl:"logika", en:"logic", scope:"skills"},
{pl:"logiczny", en:"logical", scope:"skills"},
{pl:"mechanik", en:"mechanic", scope:"jobs"},
{pl:"lider wojskowy", en:"military leader", scope:"jobs"},
{pl:"miłośnik natury", en:"nature lover", scope:"traits"},
{pl:"pielęgniarka", en:"nurse", scope:"jobs"},
{pl:"pokój", en:"peace", scope:"traits"},
{pl:"spokojny", en:"peaceful", scope:"traits"},
{pl:"rozwiązujący problemy", en:"problem-solver", scope:"skills"},
{pl:"cichy", en:"quiet", scope:"traits"},
{pl:"niezawodny", en:"reliable", scope:"traits"},
{pl:"poleganie", en:"reliance", scope:"traits"},

// workplace modern
{pl:"księgowy", en:"accountant", scope:"jobs"},
{pl:"dokładny", en:"accurate", scope:"skills"},
{pl:"pracować w IT", en:"work in IT", scope:"workplace"},
{pl:"rozmowa konferencyjna", en:"conference call", scope:"workplace"},
{pl:"magazyn mody", en:"fashion magazine", scope:"workplace"},
{pl:"przemysł spożywczy", en:"food industry", scope:"workplace"},
{pl:"ogolić się", en:"have a shave", scope:"actions"},

// feelings
{pl:"zawstydzony", en:"ashamed", scope:"feelings"},
{pl:"odczuwać ulgę", en:"be relieved", scope:"feelings"},
{pl:"znudzony", en:"bored", scope:"feelings"},
{pl:"zdezorientowany", en:"confused", scope:"feelings"},
{pl:"dezorientujący", en:"confusing", scope:"feelings"},
{pl:"zachwycony", en:"delighted", scope:"feelings"},
{pl:"zniesmaczony", en:"disgusted", scope:"feelings"},
{pl:"obrzydliwy", en:"disgusting", scope:"feelings"},
{pl:"zażenowany", en:"embarrassed", scope:"feelings"},
{pl:"zachęcający", en:"encouraging", scope:"feelings"},
{pl:"wyczerpujący", en:"exhausting", scope:"feelings"},
{pl:"wzruszony", en:"moved", scope:"feelings"},

// job search writing
{pl:"w dowolnym czasie", en:"at any time", scope:"job-search"},
{pl:"obecnie", en:"at present", scope:"job-search"},
{pl:"w tej chwili", en:"at the moment", scope:"job-search"},
{pl:"dołączyć", en:"attach", scope:"job-search"},
{pl:"dostępny", en:"available", scope:"job-search"},
{pl:"szybko się uczyć", en:"be a fast learner", scope:"skills"},
{pl:"być pewnym", en:"be confident that", scope:"skills"},
{pl:"wychowawca kolonijny", en:"camp supervisor", scope:"jobs"},
{pl:"elastyczne godziny", en:"flexible hours", scope:"work-conditions"},
{pl:"mieć doświadczenie", en:"have experience", scope:"skills"},
{pl:"w związku z", en:"in connection with", scope:"job-search"},
{pl:"rozmowa kwalifikacyjna", en:"interview", scope:"job-search"},
{pl:"ogłoszenie o pracę", en:"job advert", scope:"job-search"},
{pl:"szukać pracy", en:"look for a job", scope:"job-search"},
{pl:"uzyskać", en:"obtain", scope:"actions"},
{pl:"okazja", en:"opportunity", scope:"job-search"},
{pl:"stanowisko", en:"position", scope:"employment"},
{pl:"posiadać umiejętności", en:"possess skills", scope:"skills"},
{pl:"wymagać", en:"require", scope:"employment"},
{pl:"odnieść sukces", en:"succeed", scope:"employment"},
{pl:"odpowiedni kandydat", en:"suitable candidate", scope:"job-search"},
{pl:"w odniesieniu do", en:"with reference to", scope:"job-search"},

// speaking
{pl:"stowarzyszenie", en:"association", scope:"workplace"},
{pl:"wzór do naśladowania", en:"role model", scope:"skills"},
{pl:"wypatrywać", en:"scout", scope:"work-conditions"}
]
