export const vocab = [
{pl: "źródło", en: "a source", scope: "bhp-osp-it"},
{pl: "członek rodziny", en: "a family member", scope: "bhp-osp-it"},
{pl: "napaść, atak", en: "an attack", scope: "bhp-osp-it"},
{pl: "koń trojański", en: "a trojan horse", scope: "bhp-osp-it"},
{pl: "kraść", en: "to steal", scope: "bhp-osp-it"},
{pl: "zawierać", en: "to contain", scope: "bhp-osp-it"},
{pl: "oszukańczy", en: "fraudulent", scope: "bhp-osp-it"},
{pl: "niepożądany, natrętny", en: "intrusive", scope: "bhp-osp-it"},
{pl: "niedoskonałość", en: "an imperfection", scope: "bhp-osp-it"},
{pl: "mieć dostęp", en: "to access", scope: "bhp-osp-it"},
{pl: "poprawka", en: "a patch", scope: "bhp-osp-it"},
{pl: "zakres", en: "a scope of", scope: "bhp-osp-it"},
{pl: "albo … albo …", en: "either … or …", scope: "bhp-osp-it"},
{pl: "unieruchamiać, blokować", en: "to disable", scope: "bhp-osp-it"},
{pl: "przekręt", en: "a scam", scope: "bhp-osp-it"},
{pl: "ilość", en: "an amount of", scope: "bhp-osp-it"},
{pl: "na przecenie", en: "at a discount", scope: "bhp-osp-it"},
{pl: "w zamian", en: "in return", scope: "bhp-osp-it"},
{pl: "prosić się o kłopoty", en: "to ask for trouble", scope: "bhp-osp-it"},
{pl: "uzyskać dostęp do czegoś", en: "to get access to sth", scope: "bhp-osp-it"},
{pl: "trwać wieki", en: "to last forever", scope: "bhp-osp-it"},
{pl: "chociaż", en: "although", scope: "bhp-osp-it"},
{pl: "wielkie litery", en: "upper case letters", scope: "bhp-osp-it"},
{pl: "liczebnik", en: "a numeral", scope: "bhp-osp-it"},
{pl: "nie do pobicia", en: "unbeatable", scope: "bhp-osp-it"},
{pl: "mający reputację", en: "reputable", scope: "bhp-osp-it"},
{pl: "zamieszczać w internecie", en: "to post", scope: "bhp-osp-it"},
{pl: "sprawdzona zasada", en: "a rule of thumb", scope: "bhp-osp-it"},
{pl: "przywłaszczenie tożsamości", en: "an identity theft", scope: "bhp-osp-it"},
{pl: "powiadomienie", en: "a notification", scope: "bhp-osp-it"},
{pl: "tarcza", en: "a shield", scope: "bhp-osp-it"},
{pl: "ustawiać", en: "to configure", scope: "bhp-osp-it"},
{pl: "interfejs", en: "an interface", scope: "bhp-osp-it"},
{pl: "intruz", en: "an intruder", scope: "bhp-osp-it"},
{pl: "zapora sieciowa", en: "a firewall", scope: "bhp-osp-it"},
{pl: "kliknąć prawym przyciskiem myszy", en: "to right-click", scope: "bhp-osp-it"},
{pl: "porównywać", en: "to compare", scope: "bhp-osp-it"},
{pl: "załącznik", en: "an attachment", scope: "bhp-osp-it"},
{pl: "trzymać kogoś z dala", en: "to keep sb away", scope: "bhp-osp-it"},
{pl: "umiejscowić", en: "to place", scope: "bhp-osp-it"},
{pl: "słaby punkt", en: "a vulnerability", scope: "bhp-osp-it"},
{pl: "odkryć", en: "to discover", scope: "bhp-osp-it"},
{pl: "rozległy, nieprzebrany", en: "vast", scope: "bhp-osp-it"},
{pl: "samokopiujący się", en: "self-replication", scope: "bhp-osp-it"},
{pl: "na szczęście", en: "luckily", scope: "bhp-osp-it"},
{pl: "żart, oszustwo", en: "a hoax", scope: "bhp-osp-it"},
{pl: "fałszywy", en: "fake", scope: "bhp-osp-it"},
{pl: "próg", en: "a doorstep", scope: "bhp-osp-it"},
{pl: "apteka", en: "a pharmacy", scope: "bhp-osp-it"},
{pl: "przesłać dalej", en: "to forward", scope: "bhp-osp-it"},
{pl: "włamać się do", en: "to break into", scope: "bhp-osp-it"},
{pl: "kluczowy", en: "key", scope: "bhp-osp-it"},
{pl: "postawić hipotezę", en: "to make an educated guess", scope: "bhp-osp-it"},
{pl: "losowy", en: "random", scope: "bhp-osp-it"},
{pl: "małe litery", en: "lower case letters", scope: "bhp-osp-it"},
{pl: "znak interpunkcyjny", en: "a punctuation mark", scope: "bhp-osp-it"},
{pl: "szyfrować", en: "to encrypt", scope: "bhp-osp-it"},
{pl: "jednakże", en: "however", scope: "bhp-osp-it"},
{pl: "obcy", en: "a stranger", scope: "bhp-osp-it"},
{pl: "unikać", en: "to avoid", scope: "bhp-osp-it"},
{pl: "prosty", en: "straightforward", scope: "bhp-osp-it"},
{pl: "domyślnie", en: "by default", scope: "bhp-osp-it"},
{pl: "wprowadzać na rynek", en: "to launch", scope: "bhp-osp-it"},
{pl: "złośliwy", en: "malicious", scope: "bhp-osp-it"},
{pl: "w czasie rzeczywistym", en: "in real-time", scope: "bhp-osp-it"},
{pl: "śledzić, obserwować", en: "to monitor", scope: "bhp-osp-it"},
{pl: "oprogramowanie szantażujące", en: "ransomware", scope: "bhp-osp-it"},
{pl: "dwukrotnie kliknąć", en: "to double-click", scope: "bhp-osp-it"},
{pl: "bot", en: "a bot", scope: "bhp-osp-it"},
{pl: "program szpiegujący", en: "spyware", scope: "bhp-osp-it"},
{pl: "wymagać, angażować", en: "to involve", scope: "bhp-osp-it"},
{pl: "ukrywać", en: "to mask", scope: "bhp-osp-it"},
{pl: "wywoływać alarm", en: "to alert", scope: "bhp-osp-it"},
{pl: "zdalnie", en: "remotely", scope: "bhp-osp-it"},
{pl: "rootkit", en: "a rootkit", scope: "bhp-osp-it"},
{pl: "popełnić przestępstwo", en: "to commit a crime", scope: "bhp-osp-it"},
{pl: "osadzać, wbudować", en: "to embed", scope: "bhp-osp-it"},
{pl: "złośliwe oprogramowanie", en: "malware", scope: "bhp-osp-it"},
{pl: "przejąć kontrolę", en: "to take over", scope: "bhp-osp-it"},
{pl: "zarazić, zainfekować", en: "to infect", scope: "bhp-osp-it"},
{pl: "robak komputerowy", en: "a computer worm", scope: "bhp-osp-it"},
{pl: "wykryć", en: "to detect", scope: "bhp-osp-it"},
{pl: "wiadomość błyskawiczna", en: "an instant message", scope: "bhp-osp-it"}
]